services:
  panszelescik:
    container_name: panszelescik
    build:
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - panszelescik_network
networks:
  panszelescik_network:
    driver: bridge